name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: autoconf && ./configure
    - name: Check config
      run: ls
    - name: Compile
      run: make all
    - name: Test
      run: ./main
