<<<<<<< HEAD
name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: make all
    - name: Test
      run: ./main
=======
name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: sudo apt install autoheader && autoheader
    - name: Check config
      run: cat configure
    - name: Compile
      run: make all
    - name: Test
      run: ./main
>>>>>>> 08315c4e5553c693aa5ffb7ad1d519f9f3473535
