name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello There! We see this is your first time opening an issue! Keep in mind that the software in the depot-sinjoh repository is not designed for end-users.'
        pr-message: 'Thanks for commiting! A developer will review your PR soon :)'
