name: Test Enviroment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: ./sinjohshell.sh create && ./sinjohshell/Scripts/activate && ./sinjohshell/Scripts/deactivate
