name: Test Enviroment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: chmod +x sinjohshell.sh && ./sinjohshell.sh create && source ./sinjohshell/bin/activate && deactivate
